"""Stub: coze_coding_utils.helper.stream_runner"""
from typing import Any, Callable

class RunOpt:
    ...

class AgentStreamRunner:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class WorkflowStreamRunner:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def agent_stream_handler(*args: Any, **kwargs: Any) -> Any: ...
def workflow_stream_handler(*args: Any, **kwargs: Any) -> Any: ...
